### PR TITLE
Player: fix double audio in Firefox

### LINKED ISSUE #147: Receiver: volume slider does not work when opening a public room from Home (Firefox)
Upon opening a Public Room from the homepage, the volume slider doesn't fully go to 0% or 100% -- it does appear to change the volume slightly, but it is impossible to mute. Pressing pause also does not stop the music.

The weird behaviour of the volume & play button could very well be explained by #145; if I'm correct, then the double streaming issue would be occurring more often in Firefox.

**Environment**: Firefox 73.0.1, Linux / Ubuntu "eoan" derivative

**Workaround:** Refreshing the page while the receiver page is open fixes the issue, or using another browser like Google Chrome.

### PR DESCRIPTION
**Pull request by samtheprogram**
Solves the double audio fix by stopping the original tracks after they have been cloned; this doesn't work in Chrome, so this is only applied in Firefox. This also disables the Chrome double audio fix in Firefox, as it is not needed.

In order to distinguish Firefox from other browsers, I'm using the same method RTCMultiConnection does: the existence of `navigator.mozGetUserMedia`. Alternative suggestions are welcome.

Closes #147

### CODE REVIEW

File: src/components/Player/Player.vue [hunk 1]
```diff
@@ -26,7 +26,6 @@
       :class="{ 'mt-20': stream.isVideo }"
       :isVideo="stream.isVideo"
       :player="player"
-      :autoplay.sync="autoplay"
```
Comment (samtheprogram) [inline src/components/Player/Player.vue:29]: This change snuck in -- `autoplay` is no longer defined on MediaControls, so this code doesn't do anything and I've removed it.
